### ISSUE TITLE
All text sorrounded in blockquotes looks weird in certain readers

### ISSUE THREAD

**Issue by joelchrono12** [standardebooks/bram-stoker_dracula#11]
I read the error reporting page but it didn't mention what to do with html or displaying errors, so I decided to open an issue, please remove if this is not the way to do so.

Since quotes have less characters per line, or bigger side margins (not really sure how to say it, but I guess you guys understand) and basically the whole book's text is inside of `<blockquote>` elements, some readers display everything in italics and a bit more cramped, which makes it annoying to read.

Honestly, this only happened using the ReadEra app so far (I have been testing various reader apps lately), so maybe its not that big of a problem? But I still wonder if its actually necessary to sorround all text in blockquotes just because its a diary entry.

**Comment by acabal** [comment]
The CSS in this ebook removes margins on blockquotes; see https://github.com/standardebooks/bram-stoker_dracula/blob/38f8a273dc2b0b70236374659ed4c7e3e1c0df5e/src/epub/css/local.css#L89

Additionally, we don't add italics to blockquotes; that's something your ereader is doing. So, if your ereader is making strange formatting choices for blockquotes, and also not respecting the ebook's CSS, then one option might be to use a different ereading program. Unfortunately because ereaders often make strange choices like this, there is no ebook that will look perfect in every single ereader.

**Comment by acabal** [comment]
Also make sure you're using the compatible epub, and not the advanced epub. The advanced epub really only works with iBooks right now.

**Comment by joelchrono12** [comment]
Thanks, yeah I found a good reader now, I will submit some feedback to the app developer then, thank you.
